import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Badru-Zaman General Transport',
  description: 'Generated by Mehrab Tarrar',
  
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body className='px-3 shadow-lg'>
        <Header />
        
        {children}
        <Footer/>
        </body>
    </html>
  )
}
